objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Close_AR__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <infoMessage>The accounting period must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Project_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The organization you would like to pay you for your product or service.</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Billing__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
    <label>Billing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/AcctSeed__Billing__c/fields/AcctSeed__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
    <label>Ledger</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Ledger__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Ledger must be active</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Billing__c/fields/AcctSeed__Sales_Tax3__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Sales_Tax3__c</fullName>
    <description>Summary of the Billing Lines&apos; Tax Amount fields</description>
    <inlineHelpText>Summary of the Billing Lines&apos; Tax Amount fields</inlineHelpText>
    <label>Sales Tax</label>
    <summarizedField>AcctSeed__Billing_Line__c.AcctSeed__Tax_Amount2__c</summarizedField>
    <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/AcctSeed__Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals and invoices that are in process of being finalized. A posted status indicates the invoice is final and no further changes are to be made.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/AcctSeed__Journal_Entry__c/AcctSeed__Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to document accounting related entries into the transaction table.</description>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Journal Entry</relationshipLabel>
    <relationshipName>Journal_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Journal_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Journal_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>Informational field only to note date journal is created.</inlineHelpText>
    <label>Journal Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the associated ledger.</description>
    <label>Ledger</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Ledger__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Ledger must be active</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Reference__c</fullName>
    <description>Used to capture any external source document identifier or description.</description>
    <inlineHelpText>Used to capture any external source document identifier or description.</inlineHelpText>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>A value of &quot;Posted&quot; indicates the record is final.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/AcctSeed__Journal_Entry__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/AcctSeed__Journal_Entry_Line__c.object-meta.xml
<CustomObject>
    <description>Line level entry associated with a journal entry. The aggregation of multiple journal entry lines constitute a journal entry record.</description>
    <label>Journal Entry Line</label>
    <nameField>
        <displayFormat>JEL-{00000}</displayFormat>
        <label>Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related Customer or Vendor</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <inlineHelpText>Used to record date of entry for transaction reporting and Bank Reconciliation.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Debit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Debit__c</fullName>
    <inlineHelpText>The left side of a double entry accounting transaction. Represented as a positive amount in the transactions table.</inlineHelpText>
    <label>Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The credit GL Account used to record the transaction in the general ledger.</inlineHelpText>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet</value>
        </filterItems>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Journal_Entry__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Journal_Entry__c</fullName>
    <inlineHelpText>Parent record for this line.</inlineHelpText>
    <label>Journal Entry</label>
    <referenceTo>AcctSeed__Journal_Entry__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Ledger__c</fullName>
    <formula>AcctSeed__Journal_Entry__r.AcctSeed__Ledger__c</formula>
    <label>Ledger</label>
    <type>Text</type>
</CustomField>

objects/Avalara_API__c/Avalara_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Avalara_API</label>
</CustomObject>

objects/Avalara_API__c/fields/Base_End_Point__c.field-meta.xml
<CustomField>
    <fullName>Base_End_Point__c</fullName>
    <label>Base End Point</label>
    <type>Url</type>
</CustomField>

classes/PostAvalaraAndCreateJEQueable.cls
public with sharing class PostAvalaraAndCreateJEQueable implements Queueable, Database.AllowsCallouts{
    AcctSeed__Billing__c acctBilling= new AcctSeed__Billing__c();
    public String accountId;
    public String authToken;
    public String BaseEndpoint;
    public string commitOrUncommit;
    public PostAvalaraAndCreateJEQueable(AcctSeed__Billing__c billing,string commitOrUncommit) {
        this.acctBilling = billing;
        Avalara_API__c avalApi = Avalara_API__c.getInstance();
        this.accountId = avalApi.Account_Id__c;
        this.authToken = avalApi.Auth_Token__c;
        this.BaseEndpoint= avalApi.Base_End_Point__c;
        this.commitOrUncommit=commitOrUncommit;
      
    }
    public void execute(QueueableContext qc) {
        try{
                HttpResponse response;
                Http http;
                HttpRequest req;          
                if(this.commitOrUncommit=='commit'){

                     response = new HttpResponse();

                     http = new Http();
                     req = new HttpRequest();               
                    String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(accountId +':'+authToken));
                    req.setEndpoint(this.BaseEndpoint+'/companies/MAE-BAKERSFEILD/transactions/Billing - '+this.acctBilling.Name+'/commit');

                    req.setMethod('POST');
                    req.setHeader('Content-Type','application/json');
                    req.setHeader('Authorization',authorizationHeader);
                    req.setBody('{"commit":true}');
                    response = http.send(req);
                    if(response.getStatusCode() == 201 || response.getStatusCode() == 200){
                        List<AcctSeed__Journal_Entry_Line__c> jrnlEntryLinesList = new List<AcctSeed__Journal_Entry_Line__c>();
                        this.acctBilling=[Select Id,Name, AcctSeed__Sales_Tax3__c,AcctSeed__Accounting_Period__c,AcctSeed__Ledger__c,AcctSeed__Customer__c from  AcctSeed__Billing__c where id=:this.acctBilling.Id];
                        AcctSeed__GL_Account__c acctReceivable=[select id from AcctSeed__GL_Account__c where Name='50-Accounts Receivable(A/R)'];
                        AcctSeed__GL_Account__c acctSalesTaxPayable=[select id from AcctSeed__GL_Account__c where Name='67-Sales Tax Payable'];
                        AcctSeed__Journal_Entry__c[] journalEntries = new List <AcctSeed__Journal_Entry__c>();

                        AcctSeed__Journal_Entry__c jrnlEntryRec = new AcctSeed__Journal_Entry__c();
                        jrnlEntryRec.Name = this.acctBilling.Name;
                        jrnlEntryRec.AcctSeed__Journal_Date__c = System.Today();
                    // jrnlEntryRec.AcctSeed__Reference__c = salesRec.Salesforce_Project__r.Name+' - '+salesRec.Name+' - Commission Gross up';
                        jrnlEntryRec.AcctSeed__Status__c = 'Approved';

                        jrnlEntryRec.AcctSeed__Ledger__c=this.acctBilling.AcctSeed__Ledger__c;
                        jrnlEntryRec.Billing__c = this.acctBilling.Id;
                        jrnlEntryRec.AcctSeed__Accounting_Period__c = this.acctBilling.AcctSeed__Accounting_Period__c;
                        journalEntries.add(jrnlEntryRec);

                        insert journalEntries;
                        for (AcctSeed__Journal_Entry__c journalEntry : journalEntries) {
                            AcctSeed__Journal_Entry_Line__c firstJrnlEntrylineRec = new AcctSeed__Journal_Entry_Line__c();
                            firstJrnlEntrylineRec.AcctSeed__Journal_Entry__c=jrnlEntryRec.Id;
                            firstJrnlEntrylineRec.AcctSeed__Date__c = system.today();
                            firstJrnlEntrylineRec.AcctSeed__GL_Account__c = acctReceivable.Id;
                            firstJrnlEntrylineRec.AcctSeed__Debit__c = this.acctBilling.AcctSeed__Sales_Tax3__c;
                            firstJrnlEntrylineRec.AcctSeed__Account__c = this.acctBilling.AcctSeed__Customer__c;
                            jrnlEntryLinesList.add(firstJrnlEntrylineRec);

                            AcctSeed__Journal_Entry_Line__c secondjrnlEntrylineRec = new AcctSeed__Journal_Entry_Line__c();
                            secondjrnlEntrylineRec.AcctSeed__Journal_Entry__c=jrnlEntryRec.Id;
                            secondjrnlEntrylineRec.AcctSeed__Date__c = system.today();
                            secondjrnlEntrylineRec.AcctSeed__GL_Account__c = acctSalesTaxPayable.Id;
                            secondjrnlEntrylineRec.AcctSeed__Credit__c = this.acctBilling.AcctSeed__Sales_Tax3__c;
                            secondjrnlEntrylineRec.AcctSeed__Account__c = this.acctBilling.AcctSeed__Customer__c;
                            jrnlEntryLinesList.add(secondjrnlEntrylineRec);
                        }
                        insert jrnlEntryLinesList;

                        AcctSeed.PostResult[] postResults = AcctSeed.JournalEntryPostService.postJournalEntries(journalEntries);
                    }
                }else if(this.commitOrUncommit=='uncommit'){
                    AcctSeed__Journal_Entry__c[] journalEntries = [Select Id from AcctSeed__Journal_Entry__c where Billing__c=:this.acctBilling.Id];
                    AcctSeed.PostResult[] unpostResults = AcctSeed.JournalEntryPostService.unpostJournalEntries(journalEntries);
                

                    for (AcctSeed.PostResult theResult : unpostResults) {
                        if (theResult.isSuccess) {
                            calloutforUncommit(theResult.id,this.accountId,this.authToken,this.acctBilling.Name,this.BaseEndpoint);
                            
                        } 

                    }
                }
            }catch(Exception Ex){

            }
        }

        @future(callout = true)
        public static void calloutforUncommit(Id journalEntryId,String accountId,String authToken,String billingName,string baseEndPoint){
            HttpResponse response = new HttpResponse();
            Http http = new Http();
            HttpRequest req = new HttpRequest();     
                String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(accountId +':'+authToken));
                req.setEndpoint(baseEndPoint+'/companies/MAE-BAKERSFEILD/transactions/Billing - '+billingName+'/uncommit?documentType=1');

                req.setMethod('POST');
                req.setHeader('Content-Type','application/json');
                req.setHeader('Authorization',authorizationHeader);
                        
                response = http.send(req);
                if(response.getStatusCode() == 201 || response.getStatusCode() == 200){
                    AcctSeed__Journal_Entry__c[] journalEntries=[Select Id from AcctSeed__Journal_Entry__c where id=:journalEntryId];
                    Delete journalEntries;
                } 
        }
        
    
    
}