objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Quantity Available</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Quantity Available Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Quantity Available</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Location__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeedERP__Location__c.AcctSeedERP__Warehouse__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Warehouse__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Location__c/AcctSeedERP__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Location__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Woocommerce_IQA_API__c/Woocommerce_IQA_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Woocommerce IQA API Details</label>
</CustomObject>

objects/Woocommerce_IQA_API__c/fields/header__c.field-meta.xml
<CustomField>
    <fullName>header__c</fullName>
    <label>header</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/Woocommerce_IQA_API__c/fields/Sync_URL__c.field-meta.xml
<CustomField>
    <fullName>Sync_URL__c</fullName>
    <label>Sync URL</label>
    <type>Url</type>
</CustomField>

classes/InventoryBalanceCallout.cls
public with sharing class InventoryBalanceCallout {
    @Future(callout=true)
    public static void post( set<Id> inventoryBalanceId) {
        Set<String> setProductSKU= new Set<String>();
        Set<String> setWareHouseName= new Set<String>();
        for(AcctSeedERP__Inventory_Balance__c inventoryBalance: [SELECT AcctSeedERP__Location__r.Name,AcctSeedERP__Available_Quantity__c,AcctSeedERP__Warehouse__r.Name,AcctSeedERP__Product__c,AcctSeedERP__Product__r.StockKeepingUnit   from AcctSeedERP__Inventory_Balance__c where id in :inventoryBalanceId]){
            setProductSKU.add(inventoryBalance.AcctSeedERP__Product__r.StockKeepingUnit);
            setWareHouseName.add(inventoryBalance.AcctSeedERP__Warehouse__r.Name);
        }

        Woocommerce_IQA_API__c creds = Woocommerce_IQA_API__c.getOrgDefaults();

        for(AggregateResult ar: [select sum(AcctSeedERP__Available_Quantity__c), AcctSeedERP__Warehouse__c, AcctSeedERP__Product__r.StockKeepingUnit,AcctSeedERP__Warehouse__r.Name  from AcctSeedERP__Inventory_Balance__c where AcctSeedERP__Product__r.StockKeepingUnit in :setProductSKU and AcctSeedERP__Warehouse__r.Name in :setWareHouseName  group by AcctSeedERP__Warehouse__c,AcctSeedERP__Product__r.StockKeepingUnit,AcctSeedERP__Warehouse__r.Name]){
            
            ProductData objPRod= new ProductData();       
            List<cls_ProductData> lstclsPrd= new List<cls_ProductData>();
             cls_ProductData clsPrd= new cls_ProductData();
            clsPrd.product_sku=String.Valueof(ar.get('StockKeepingUnit'));
            clsPrd.warehouse_id=String.Valueof(ar.get('AcctSeedERP__Warehouse__c'));
            clsPrd.stock_available=String.Valueof( ar.get('expr0'));
            lstclsPrd.add(clsPrd);       
            objPRod.ProductData=lstclsPrd;
            try {
                Http http = new Http();
                HttpRequest request = new HttpRequest();               
                Blob headerValue = Blob.valueOf(creds.header__c);
                request.setEndpoint(creds.Sync_URL__c);
                request.setMethod('POST');
                request.setHeader('Content-Type','application/json');
                request.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(headerValue));
                request.setBody(JSON.serialize(objPRod));
                HttpResponse response = http.send(request);
                
                
                
            } catch (Exception Ex) {
                System.debug('Ex   >>>>'+Ex.getMessage());
            }
        }
    }


    class ProductData {
        public cls_ProductData[] ProductData;        
    }
    class cls_ProductData {
            public String product_sku;	
            public String warehouse_id;	
            public String stock_available;	
        }
}