objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Quantity Available</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Quantity Available Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Quantity Available</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Location__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeedERP__Location__c.AcctSeedERP__Warehouse__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Warehouse__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Sales_Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order_Quantity__c</fullName>
    <label>Sales Order Quantity</label>
    <summarizedField>AcctSeedERP__Sales_Order_Inventory_Movement__c.AcctSeedERP__Quantity__c</summarizedField>
    <summaryForeignKey>AcctSeedERP__Sales_Order_Inventory_Movement__c.AcctSeedERP__Inventory_Balance__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Inventory_Balance__c/fields/Qty_Available__c.field-meta.xml
<CustomField>
    <fullName>Qty_Available__c</fullName>
    <label>Qty Available</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/AcctSeedERP__Location__c/AcctSeedERP__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Location__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Looking_for__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Store Pick up</fullName>
            </value>
            <value>
                <fullName>Door Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Opportunity/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Opportunity/recordTypes/opportunity.recordType-meta.xml
<RecordType>
    <fullName>opportunity</fullName>
    <active>true</active>
    <businessProcess>opportunity read</businessProcess>
    <label>B2B Opportunity</label>
</RecordType>

objects/Product2/fields/AXLE_POSITION__c.field-meta.xml
<CustomField>
    <fullName>AXLE_POSITION__c</fullName>
    <label>Axle Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DRIVE</fullName>
                <label>Drive</label>
            </value>
            <value>
                <fullName>STEER</fullName>
                <label>Steer</label>
            </value>
            <value>
                <fullName>ALL POSITION</fullName>
                <label>All Position</label>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/Product_Master__c.field-meta.xml
<CustomField>
    <fullName>Product_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Master</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Quote/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fitment</fullName>
            </value>
            <value>
                <fullName>Delivery without Liftgate</fullName>
            </value>
            <value>
                <fullName>Delivery with Liftgate</fullName>
            </value>
            <value>
                <fullName>Self - Pickup</fullName>
            </value>
            <value>
                <fullName>Door Delivery</fullName>
            </value>
            <value>
                <fullName>Store Pick Up</fullName>
            </value>
            <value>
                <fullName>Delivery Lift Gate Not Required</fullName>
                <isActive>false</isActive>
                <label>Delivery Lift Gate Not Required</label>
            </value>
            <value>
                <fullName>Delivery Lift Gate Required</fullName>
                <isActive>false</isActive>
                <label>Delivery Lift Gate Required</label>
            </value>
            <value>
                <fullName>Self-Pickup</fullName>
                <isActive>false</isActive>
                <label>Self-Pickup</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Quote/fields/Warehouse_Location__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Location</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Quotes (Warehouse Location)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/LocationWiseInverntoryController.cls
public with sharing class LocationWiseInverntoryController {
    @AuraEnabled
    public static List<Warehouse> getRelevantWarehouses(Id opportunityId){
        List<Warehouse> warehouses = new List<Warehouse>();
        System.debug('========== Method Called ==========');
        System.debug('Opportunity Id : ' + opportunityId);
        
        String sObjName = opportunityId.getSObjectType().getDescribe().getName();
        
        String warehouseId = null;
        String warehouseState = null;
        if(String.isNotBlank(opportunityId)){
            Map<String, String> allProducts = new Map<String, String>();
            //Set<String> allLocationIds = new Set<String>();
            Set<String> allWarehouseIds = new Set<String>();
            if(sObjName == 'Opportunity'){
                for(Opportunity opp : [Select Id, Warehouse_Location__c, Warehouse_Location__r.Name, Delivery_Type__c, Account.ShippingState, (Select id, Name, product2Id, Product2.Name,Product2.Product_Master__r.Name,Product2.Product_Master__c,Product2.Product_Type__c from opportunityLineItems where product2.Family = 'Sales Product') from Opportunity where Id =: opportunityId]){
                    if(opp.Delivery_Type__c == 'Door Delivery'){
                        warehouseState = opp.Account.ShippingState;
                    }else{
                        warehouseId = opp.Warehouse_Location__c;
                    }
                    
                    if(opp.opportunityLineItems.size() > 0){
                        for(opportunityLineItem lineItem : opp.opportunityLineItems){
                            if(lineItem.Product2.Product_Type__c == 'Base Product'){
                                allProducts.put(lineItem.product2Id, lineItem.Product2.Name);
                            }else if(lineItem.Product2.Product_Type__c == 'kit Product'){
                                allProducts.put(lineItem.Product2.Product_Master__c, lineItem.Product2.Name);
                            }
                        }
                    }
                } 
            }
            else if(sObjName == 'Quote'){
                for(Quote qte : [Select Id, Opportunity.Warehouse_Location__c, Opportunity.Warehouse_Location__r.Name,Opportunity.Delivery_Type__c, Opportunity.Account.ShippingState, (Select id, product2Id, Product2.Name,Product2.Product_Master__r.Name,Product2.Product_Master__c,Product2.Product_Type__c from QuoteLineItems where product2.Family = 'Sales Product') from quote where Id =: opportunityId]){
                    if(qte.Opportunity.Delivery_Type__c == 'Door Delivery'){
                        warehouseState = qte.Opportunity.Account.ShippingState;
                    }else{
                        warehouseId = qte.Opportunity.Warehouse_Location__c;
                    }
                    
                    if(qte.QuoteLineItems.size() > 0){
                        for(QuoteLineItem lineItem : qte.QuoteLineItems){
                            if(lineItem.Product2.Product_Type__c == 'Base Product'){
                                allProducts.put(lineItem.product2Id, lineItem.Product2.Name);
                            }else if(lineItem.Product2.Product_Type__c == 'kit Product'){
                                allProducts.put(lineItem.Product2.Product_Master__c, lineItem.Product2.Name);
                            }
                        }
                    }
                    
                }
            }
            System.debug('Checkpoint - 1');
            System.debug(warehouseId);
            System.debug(warehouseState);
            System.debug(allProducts);

            List<AcctSeedERP__Warehouse__c> relevantWarehouseRecords = new List<AcctSeedERP__Warehouse__c>();
            if(String.isNotBlank(warehouseId)){
                for(AcctSeedERP__Warehouse__c warehouseRecord : [Select id, Name, (Select id, Name from AcctSeedERP__Locations__r) from AcctSeedERP__Warehouse__c where Id =: warehouseId]){
                    /*if(warehouseRecord.AcctSeedERP__Locations__r.size() > 0){
                        for(AcctSeedERP__Location__c location : warehouseRecord.AcctSeedERP__Locations__r){
                        	allLocationIds.add(location.Id);
                        }
                    }*/
                    allWarehouseIds.add(warehouseRecord.Id);
                    relevantWarehouseRecords.add(warehouseRecord);
                }
            //}else if(String.isNotBlank(warehouseState)){ // Commented this condition as warehouseState is not used further in any condition.
            }else{
                for(AcctSeedERP__Warehouse__c warehouseRecord : [Select id, Name, (Select id, Name from AcctSeedERP__Locations__r) from AcctSeedERP__Warehouse__c]){
                    /*if(warehouseRecord.AcctSeedERP__Locations__r.size() > 0){
                        for(AcctSeedERP__Location__c location : warehouseRecord.AcctSeedERP__Locations__r){
                        	allLocationIds.add(location.Id);
                        }
                    }*/
                    allWarehouseIds.add(warehouseRecord.Id);
                    relevantWarehouseRecords.add(warehouseRecord);
                }
            }
            System.debug('Checkpoint - 2');
            System.debug(allWarehouseIds);
            System.debug(relevantWarehouseRecords);
            Map<String, AcctSeedERP__Inventory_Balance__c> prodBalceMap = new Map<String, AcctSeedERP__Inventory_Balance__c>();
            Map<String, Map<String, Decimal>> warehouseProductQtyMap = new Map<String, Map<String, Decimal>>();
            //Map<String, List<AcctSeedERP__Inventory_Balance__c>> locationToBalanceMap = new Map<String, List<AcctSeedERP__Inventory_Balance__c>>();
            for(AcctSeedERP__Inventory_Balance__c InventoryBalance : [Select id, Qty_Available__c, AcctSeedERP__Available_Quantity__c, AcctSeedERP__Sales_Order_Quantity__c,AcctSeedERP__Warehouse__c, AcctSeedERP__Product__c, AcctSeedERP__Product__r.AXLE_POSITION__c,AcctSeedERP__Product__r.Name, AcctSeedERP__Location__c from AcctSeedERP__Inventory_Balance__c where AcctSeedERP__Warehouse__c IN: allWarehouseIds]){//AcctSeedERP__Product__c IN: allProducts.keySet() AND
                /*if(!locationToBalanceMap.containsKey(InventoryBalance.AcctSeedERP__Location__c)){
                    locationToBalanceMap.put(InventoryBalance.AcctSeedERP__Location__c, new List<AcctSeedERP__Inventory_Balance__c>());
                }
                locationToBalanceMap.get(InventoryBalance.AcctSeedERP__Location__c).add(InventoryBalance);*/
                if(!warehouseProductQtyMap.containsKey(InventoryBalance.AcctSeedERP__Warehouse__c)){
                    warehouseProductQtyMap.put(InventoryBalance.AcctSeedERP__Warehouse__c, new Map<String, Decimal>());
                    warehouseProductQtyMap.get(InventoryBalance.AcctSeedERP__Warehouse__c).put(InventoryBalance.AcctSeedERP__Product__c, InventoryBalance.AcctSeedERP__Available_Quantity__c);
                }else if(!warehouseProductQtyMap.get(InventoryBalance.AcctSeedERP__Warehouse__c).containsKey(InventoryBalance.AcctSeedERP__Product__c)){
                    warehouseProductQtyMap.get(InventoryBalance.AcctSeedERP__Warehouse__c).put(InventoryBalance.AcctSeedERP__Product__c, InventoryBalance.AcctSeedERP__Available_Quantity__c);
                }else {
                    Decimal qtyToIncrement = warehouseProductQtyMap.get(InventoryBalance.AcctSeedERP__Warehouse__c).get(InventoryBalance.AcctSeedERP__Product__c)+InventoryBalance.AcctSeedERP__Available_Quantity__c;
                    warehouseProductQtyMap.get(InventoryBalance.AcctSeedERP__Warehouse__c).put(InventoryBalance.AcctSeedERP__Product__c, qtyToIncrement);
                }
                prodBalceMap.put(InventoryBalance.AcctSeedERP__Product__c, InventoryBalance);
            }
            System.debug('Checkpoint - 3');
            System.debug(prodBalceMap);
            System.debug(warehouseProductQtyMap);
            Map<String, Decimal> prodOrderedQtyMap = new Map<String, Decimal>();
            for(AcctSeedERP__Sales_Order_Line__c salesOrderLine :[Select Id, AcctSeedERP__Quantity_Ordered__c, AcctSeedERP__Product__c from AcctSeedERP__Sales_Order_Line__c where AcctSeedERP__Product__c IN: prodBalceMap.keySet()]){
                if(!prodOrderedQtyMap.containsKey(salesOrderLine.AcctSeedERP__Product__c)){
                    prodOrderedQtyMap.put(salesOrderLine.AcctSeedERP__Product__c, salesOrderLine.AcctSeedERP__Quantity_Ordered__c);
                }else{
                    Decimal ordQty = prodOrderedQtyMap.get(salesOrderLine.AcctSeedERP__Product__c) + salesOrderLine.AcctSeedERP__Quantity_Ordered__c;
                    prodOrderedQtyMap.put(salesOrderLine.AcctSeedERP__Product__c, ordQty);
                }
            }
            System.debug('Checkpoint - 4');
            System.debug(prodOrderedQtyMap);
            if(relevantWarehouseRecords.size() > 0){
                for(AcctSeedERP__Warehouse__c warehouseRecord : relevantWarehouseRecords){
                    if(warehouseProductQtyMap.containsKey(warehouseRecord.Id)){
                        Map<String, Inventory> inventories = new Map<String, Inventory>();
                        for(String productId : warehouseProductQtyMap.get(warehouseRecord.Id).keyset()){
                            Inventory inventoryVar = new Inventory();
                            inventoryVar.productId = productId;
                            inventoryVar.productName = prodBalceMap.get(productId).AcctSeedERP__Product__r.Name;
                            inventoryVar.availableQuantity = warehouseProductQtyMap.get(warehouseRecord.Id).get(productId);
                            inventoryVar.axlePosition = prodBalceMap.get(productId).AcctSeedERP__Product__r.AXLE_POSITION__c;
                            inventoryVar.allocationWaitingQuantity = prodOrderedQtyMap.get(productId);
                            if(allProducts.containsKey(productId)){
                                inventoryVar.selected = true;
                            }
                            inventories.put(productId, inventoryVar);
                        }
                        /*if(inventories.size() != allProducts.size()){
                            for(String productId : allProducts.keySet()){
                                if(!inventories.containsKey(productId)){
                                    Inventory inventoryVar = new Inventory();
                                    inventoryVar.productId = productId;
                                    inventoryVar.productName = allProducts.get(productId);
                                    inventoryVar.availableQuantity = 0;
                                    inventoryVar.allocationWaitingQuantity = 0;
                                    inventories.put(productId, inventoryVar);
                                }
                            }
                        }*/
                        Warehouse warehouseVar = new Warehouse();
                        warehouseVar.warehouseId = warehouseRecord.Id;
                        warehouseVar.warehouseName = warehouseRecord.Name;
                        warehouseVar.productLevelInventory = inventories.values();
                        warehouses.add(warehouseVar);
                    }
					System.debug('Checkpoint - 5');
            		System.debug(warehouses);
                    /*List<Location> locations = new List<Location>();
                    //if(warehouseRecord.AcctSeedERP__Locations__r.size() > 0){
                        //for(AcctSeedERP__Location__c locationRecord : warehouseRecord.AcctSeedERP__Locations__r){
                            if(warehouseToBalanceMap.containsKey(warehouseRecord.Id)){
                                Map<String, Inventory> inventories = new Map<String, Inventory>();
                                for(AcctSeedERP__Inventory_Balance__c balance : warehouseToBalanceMap.get(warehouseRecord.Id)){
                                    Inventory inventoryVar = new Inventory();
                                    inventoryVar.productId = balance.AcctSeedERP__Product__c;
                                    inventoryVar.productName = balance.AcctSeedERP__Product__r.Name;
                                    inventoryVar.availableQuantity = balance.AcctSeedERP__Available_Quantity__c;
                                    inventories.put(balance.AcctSeedERP__Product__c, inventoryVar);
                                }

                                if(inventories.size() != allProducts.size()){
                                    for(String productId : allProducts.keySet()){
                                        if(!inventories.containsKey(productId)){
                                            Inventory inventoryVar = new Inventory();
                                            inventoryVar.productId = productId;
                                            inventoryVar.productName = allProducts.get(productId);
                                            inventoryVar.availableQuantity = 0;
                                            inventories.put(productId, inventoryVar);
                                        }
                                    }
                                }


                                
                                Location locationVar = new Location();
                                locationVar.locationId = locationRecord.Id;
                                locationVar.locationName = locationRecord.Name;
                                locationVar.productLevelInventory = inventories.values();
                                locations.add(locationVar);
                            }else{
                                Map<String, Inventory> inventories = new Map<String, Inventory>();

                                for(String productId : allProducts.keySet()){
                                    Inventory inventoryVar = new Inventory();
                                    inventoryVar.productId = productId;
                                    inventoryVar.productName = allProducts.get(productId);
                                    inventoryVar.availableQuantity = 0;
                                    inventories.put(productId, inventoryVar);
                                }

                                Location locationVar = new Location();
                                locationVar.locationId = locationRecord.Id;
                                locationVar.locationName = locationRecord.Name;
                                locationVar.productLevelInventory = inventories.values();
                                locations.add(locationVar);
                            }
                        }
                    }

                    Warehouse warehouseVar = new Warehouse();
                    warehouseVar.warehouseId = warehouseRecord.Id;
                    warehouseVar.warehouseName = warehouseRecord.Name;
                    warehouseVar.locations = locations;
                    warehouses.add(warehouseVar);*/
                }
            }
        }
        
        return warehouses;
    }


    Public Class Warehouse{
        @AuraEnabled Public String warehouseId{get;set;}
        @AuraEnabled Public String warehouseName{get;set;}
        @AuraEnabled Public Boolean isDrawerOpen{get;set;}
        @AuraEnabled Public List<Inventory> productLevelInventory{get;set;}
        //@AuraEnabled Public List<Location> locations{get;set;}

        Public Warehouse(){
            this.isDrawerOpen = false;
        }
    }

    /*Public Class Location{
        @AuraEnabled Public String locationId{get;set;}
        @AuraEnabled Public String locationName{get;set;}
        @AuraEnabled Public Boolean isDrawerOpen{get;set;}
        @AuraEnabled Public List<Inventory> productLevelInventory{get;set;}

        Public Location(){
            this.isDrawerOpen = false;
        }
    }*/

    Public Class Inventory{
        @AuraEnabled Public String productId{get;set;}
        @AuraEnabled Public String productName{get;set;}
        @AuraEnabled Public Decimal availableQuantity{get;set;}
        @AuraEnabled Public Decimal allocationWaitingQuantity{get;set;}
        @AuraEnabled Public String axlePosition{get;set;}
        @AuraEnabled Public Boolean selected{get;set;}
        //@AuraEnabled Public AcctSeedERP__Inventory_Balance__c inventoryRecord{get;set;}
        public Inventory (){
            this.selected = false;
        }
    }

    Public Class Product{

    }
}