objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals and invoices that are in process of being finalized. A posted status indicates the invoice is final and no further changes are to be made.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/BillingTriggerHandler.cls
public with sharing class BillingTriggerHandler  implements ITriggerHandler {
    public Boolean IsDisabled(){		
        return false;
       
     }
  
     public void BeforeInsert(List<Sobject> newItems){

       
     
    }
     public void BeforeDelete(Map<id, sObject> oldItems){
     
     }
    
     public void AfterInsert(List<Sobject> newMap){     

     }
 
     public void AfterUpdate(Map<Id, sObject> newMap, Map<Id, sObject> oldMap){    
        Map<Id,AcctSeed__Billing__c> newItems= (Map<Id,AcctSeed__Billing__c>)newMap;
        Map<Id,AcctSeed__Billing__c> oldItems= (Map<Id,AcctSeed__Billing__c>)oldMap;
       
        try {
            for(AcctSeed__Billing__c billing: newItems.values()){
                if(billing.AcctSeed__Status__c != oldItems.get(billing.Id).AcctSeed__Status__c && billing.AcctSeed__Status__c=='Posted'){
                    System.enqueuejob(new PostAvalaraAndCreateJEQueable(billing,'commit'));
                }
                if(billing.AcctSeed__Status__c != oldItems.get(billing.Id).AcctSeed__Status__c && billing.AcctSeed__Status__c=='Approved' && oldItems.get(billing.Id).AcctSeed__Status__c == 'Posted'){
                    System.enqueuejob(new PostAvalaraAndCreateJEQueable(billing,'uncommit'));
                }
            }
           
        } catch (Exception Ex) {
            
        } finally {
            
        }
      
     }
    
     
}