objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity/recordTypes/opportunity.recordType-meta.xml
<RecordType>
    <fullName>opportunity</fullName>
    <active>true</active>
    <businessProcess>opportunity read</businessProcess>
    <label>B2B Opportunity</label>
</RecordType>

classes/CalculateTax.cls
/*
 * Test Class: CalculateTaxTest
 */
public with sharing class CalculateTax {
    @AuraEnabled
    public static ResponseWrapper calculateTax(String recordId, String objectApiName){
        ResponseWrapper returnResult = new ResponseWrapper();
        //Boolean returnResult = false;
        System.debug('Apex Called ======>');
        System.debug(objectApiName);
        if('Quote'.equalsIgnoreCase(objectApiName)){
            returnResult = CalculateTaxQuote.calculateTax(recordId);
        }else if('Opportunity'.equalsIgnoreCase(objectApiName)){
            returnResult = CalculateTaxOpportunity.calculateTax(recordId);
        }else if('AcctSeedERP__Sales_Order__c'.equalsIgnoreCase(objectApiName)){
            returnResult = CalculateTaxSalesOrder.calculateTax(recordId);
        }else if('AcctSeed__Billing__c'.equalsIgnoreCase(objectApiName)){
           returnResult = CalculateTaxBilling.calculateTax(recordId);
        }

        return returnResult;
    }
    
    public class ResponseWrapper{
        @AuraEnabled public string title {get;set;}
        @AuraEnabled public string variant {get;set;}
        @AuraEnabled public string message {get;set;}
    }
}